# This is the configuration used to check the rubocop source code.
AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Documentation:
  Enabled: false
